"""2_text_user_uuid_onupdate_cascade

Revision ID: 6a2d2c06504f
Revises: 6fafe96eb49f
Create Date: 2025-06-30 16:58:37.347156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a2d2c06504f'
down_revision = '6fafe96eb49f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('text_user_uuid_fkey', 'text', type_='foreignkey')
    op.create_foreign_key('text_user_uuid_fkey', 'text', 'user', ['user_uuid'], ['uuid'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('text_user_uuid_fkey', 'text', type_='foreignkey')
    op.create_foreign_key('text_user_uuid_fkey', 'text', 'user', ['user_uuid'], ['uuid'], ondelete='CASCADE')
    # ### end Alembic commands ###
