services:

  api_readstash:
    build:
      context: ../..
      dockerfile: ./docker/api_readstash/Dockerfile
    container_name: api_readstash
    volumes:
      - ../../api_readstash:/app/api_readstash
    networks:
      - local_network_api_readstash
      - shared_network_readstash
    healthcheck:
      test: [ "CMD-SHELL", "curl -H 'X-Request-Id: healthcheck' --fail -f http://$$API_READSTASH_HOST:$$API_READSTASH_PORT/$$DOCS_URL" ]
      interval: 10s
      timeout: 30s
      retries: 3
    environment:
      - TZ=UTC

  celery_worker_readstash:
    build:
      context: ../..
      dockerfile: ./docker/api_readstash/Dockerfile
    container_name: celery_worker_readstash
    command: /start_api_celery_worker.sh
    volumes:
      - ../../api_readstash:/app/api_readstash
    networks:
      - local_network_api_readstash
      - shared_network_readstash
    environment:
      - TZ=UTC

  celery_flower_readstash:
    build:
      context: ../..
      dockerfile: ./docker/api_readstash/Dockerfile
    command: /start_api_celery_flower.sh
    container_name: celery_flower_readstash
    volumes:
      - ../../api_readstash:/app/api_readstash
    networks:
      - local_network_api_readstash
      - shared_network_readstash
    environment:
      - TZ=UTC

#  celery_beat_readstash:
#    build:
#      context: ../..
#      dockerfile: ./docker/api_readstash/Dockerfile
#    command: /start_api_celery_beat.sh
#    container_name: celery_beat_readstash
#    volumes:
#      - ../../api_readstash:/app/api_readstash
#    networks:
#      - local_network_api_readstash
#      - shared_network_readstash
#    environment:
#      - TZ=UTC

networks:
  local_network_api_readstash:
    driver: bridge
  shared_network_readstash:
    external: true

